// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventsAndCommands.proto

package com.cruzeiro.repassedepolo.rulemanager.protobuf;

public final class EventsAndCommands {
    private EventsAndCommands() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface RuleEventOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.cruzeiro.repassedepolo.rulemanager.protobuf.RuleEvent)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string ruleId = 1;</code>
         */
        java.lang.String getRuleId();
        /**
         * <code>string ruleId = 1;</code>
         */
        com.google.protobuf.ByteString
        getRuleIdBytes();

        /**
         * <code>string ruleStatus = 2;</code>
         */
        java.lang.String getRuleStatus();
        /**
         * <code>string ruleStatus = 2;</code>
         */
        com.google.protobuf.ByteString
        getRuleStatusBytes();
    }
    /**
     * Protobuf type {@code com.cruzeiro.repassedepolo.rulemanager.protobuf.RuleEvent}
     */
    public  static final class RuleEvent extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.cruzeiro.repassedepolo.rulemanager.protobuf.RuleEvent)
            RuleEventOrBuilder {
        // Use RuleEvent.newBuilder() to construct.
        private RuleEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private RuleEvent() {
            ruleId_ = "";
            ruleStatus_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private RuleEvent(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            ruleId_ = s;
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            ruleStatus_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleEvent_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleEvent_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent.class, com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent.Builder.class);
        }

        public static final int RULEID_FIELD_NUMBER = 1;
        private volatile java.lang.Object ruleId_;
        /**
         * <code>string ruleId = 1;</code>
         */
        public java.lang.String getRuleId() {
            java.lang.Object ref = ruleId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                ruleId_ = s;
                return s;
            }
        }
        /**
         * <code>string ruleId = 1;</code>
         */
        public com.google.protobuf.ByteString
        getRuleIdBytes() {
            java.lang.Object ref = ruleId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                ruleId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int RULESTATUS_FIELD_NUMBER = 2;
        private volatile java.lang.Object ruleStatus_;
        /**
         * <code>string ruleStatus = 2;</code>
         */
        public java.lang.String getRuleStatus() {
            java.lang.Object ref = ruleStatus_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                ruleStatus_ = s;
                return s;
            }
        }
        /**
         * <code>string ruleStatus = 2;</code>
         */
        public com.google.protobuf.ByteString
        getRuleStatusBytes() {
            java.lang.Object ref = ruleStatus_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                ruleStatus_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getRuleIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ruleId_);
            }
            if (!getRuleStatusBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ruleStatus_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getRuleIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ruleId_);
            }
            if (!getRuleStatusBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ruleStatus_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent)) {
                return super.equals(obj);
            }
            com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent other = (com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent) obj;

            boolean result = true;
            result = result && getRuleId()
                    .equals(other.getRuleId());
            result = result && getRuleStatus()
                    .equals(other.getRuleStatus());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + RULEID_FIELD_NUMBER;
            hash = (53 * hash) + getRuleId().hashCode();
            hash = (37 * hash) + RULESTATUS_FIELD_NUMBER;
            hash = (53 * hash) + getRuleStatus().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code com.cruzeiro.repassedepolo.rulemanager.protobuf.RuleEvent}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.cruzeiro.repassedepolo.rulemanager.protobuf.RuleEvent)
                com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEventOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleEvent_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleEvent_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent.class, com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent.Builder.class);
            }

            // Construct using com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                ruleId_ = "";

                ruleStatus_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleEvent_descriptor;
            }

            public com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent getDefaultInstanceForType() {
                return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent.getDefaultInstance();
            }

            public com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent build() {
                com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent buildPartial() {
                com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent result = new com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent(this);
                result.ruleId_ = ruleId_;
                result.ruleStatus_ = ruleStatus_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent) {
                    return mergeFrom((com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent other) {
                if (other == com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent.getDefaultInstance()) return this;
                if (!other.getRuleId().isEmpty()) {
                    ruleId_ = other.ruleId_;
                    onChanged();
                }
                if (!other.getRuleStatus().isEmpty()) {
                    ruleStatus_ = other.ruleStatus_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object ruleId_ = "";
            /**
             * <code>string ruleId = 1;</code>
             */
            public java.lang.String getRuleId() {
                java.lang.Object ref = ruleId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    ruleId_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string ruleId = 1;</code>
             */
            public com.google.protobuf.ByteString
            getRuleIdBytes() {
                java.lang.Object ref = ruleId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    ruleId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string ruleId = 1;</code>
             */
            public Builder setRuleId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                ruleId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string ruleId = 1;</code>
             */
            public Builder clearRuleId() {

                ruleId_ = getDefaultInstance().getRuleId();
                onChanged();
                return this;
            }
            /**
             * <code>string ruleId = 1;</code>
             */
            public Builder setRuleIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                ruleId_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object ruleStatus_ = "";
            /**
             * <code>string ruleStatus = 2;</code>
             */
            public java.lang.String getRuleStatus() {
                java.lang.Object ref = ruleStatus_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    ruleStatus_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string ruleStatus = 2;</code>
             */
            public com.google.protobuf.ByteString
            getRuleStatusBytes() {
                java.lang.Object ref = ruleStatus_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    ruleStatus_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string ruleStatus = 2;</code>
             */
            public Builder setRuleStatus(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                ruleStatus_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string ruleStatus = 2;</code>
             */
            public Builder clearRuleStatus() {

                ruleStatus_ = getDefaultInstance().getRuleStatus();
                onChanged();
                return this;
            }
            /**
             * <code>string ruleStatus = 2;</code>
             */
            public Builder setRuleStatusBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                ruleStatus_ = value;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:com.cruzeiro.repassedepolo.rulemanager.protobuf.RuleEvent)
        }

        // @@protoc_insertion_point(class_scope:com.cruzeiro.repassedepolo.rulemanager.protobuf.RuleEvent)
        private static final com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent();
        }

        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<RuleEvent>
                PARSER = new com.google.protobuf.AbstractParser<RuleEvent>() {
            public RuleEvent parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new RuleEvent(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<RuleEvent> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<RuleEvent> getParserForType() {
            return PARSER;
        }

        public com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleEvent getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface ValidatedEventOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.cruzeiro.repassedepolo.rulemanager.protobuf.ValidatedEvent)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string ruleId = 1;</code>
         */
        java.lang.String getRuleId();
        /**
         * <code>string ruleId = 1;</code>
         */
        com.google.protobuf.ByteString
        getRuleIdBytes();

        /**
         * <code>string ruleStatus = 2;</code>
         */
        java.lang.String getRuleStatus();
        /**
         * <code>string ruleStatus = 2;</code>
         */
        com.google.protobuf.ByteString
        getRuleStatusBytes();
    }
    /**
     * Protobuf type {@code com.cruzeiro.repassedepolo.rulemanager.protobuf.ValidatedEvent}
     */
    public  static final class ValidatedEvent extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.cruzeiro.repassedepolo.rulemanager.protobuf.ValidatedEvent)
            ValidatedEventOrBuilder {
        // Use ValidatedEvent.newBuilder() to construct.
        private ValidatedEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private ValidatedEvent() {
            ruleId_ = "";
            ruleStatus_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private ValidatedEvent(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            ruleId_ = s;
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            ruleStatus_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_ValidatedEvent_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_ValidatedEvent_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent.class, com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent.Builder.class);
        }

        public static final int RULEID_FIELD_NUMBER = 1;
        private volatile java.lang.Object ruleId_;
        /**
         * <code>string ruleId = 1;</code>
         */
        public java.lang.String getRuleId() {
            java.lang.Object ref = ruleId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                ruleId_ = s;
                return s;
            }
        }
        /**
         * <code>string ruleId = 1;</code>
         */
        public com.google.protobuf.ByteString
        getRuleIdBytes() {
            java.lang.Object ref = ruleId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                ruleId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int RULESTATUS_FIELD_NUMBER = 2;
        private volatile java.lang.Object ruleStatus_;
        /**
         * <code>string ruleStatus = 2;</code>
         */
        public java.lang.String getRuleStatus() {
            java.lang.Object ref = ruleStatus_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                ruleStatus_ = s;
                return s;
            }
        }
        /**
         * <code>string ruleStatus = 2;</code>
         */
        public com.google.protobuf.ByteString
        getRuleStatusBytes() {
            java.lang.Object ref = ruleStatus_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                ruleStatus_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getRuleIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ruleId_);
            }
            if (!getRuleStatusBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ruleStatus_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getRuleIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ruleId_);
            }
            if (!getRuleStatusBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ruleStatus_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent)) {
                return super.equals(obj);
            }
            com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent other = (com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent) obj;

            boolean result = true;
            result = result && getRuleId()
                    .equals(other.getRuleId());
            result = result && getRuleStatus()
                    .equals(other.getRuleStatus());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + RULEID_FIELD_NUMBER;
            hash = (53 * hash) + getRuleId().hashCode();
            hash = (37 * hash) + RULESTATUS_FIELD_NUMBER;
            hash = (53 * hash) + getRuleStatus().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code com.cruzeiro.repassedepolo.rulemanager.protobuf.ValidatedEvent}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.cruzeiro.repassedepolo.rulemanager.protobuf.ValidatedEvent)
                com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEventOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_ValidatedEvent_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_ValidatedEvent_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent.class, com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent.Builder.class);
            }

            // Construct using com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                ruleId_ = "";

                ruleStatus_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_ValidatedEvent_descriptor;
            }

            public com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent getDefaultInstanceForType() {
                return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent.getDefaultInstance();
            }

            public com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent build() {
                com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent buildPartial() {
                com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent result = new com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent(this);
                result.ruleId_ = ruleId_;
                result.ruleStatus_ = ruleStatus_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent) {
                    return mergeFrom((com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent other) {
                if (other == com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent.getDefaultInstance()) return this;
                if (!other.getRuleId().isEmpty()) {
                    ruleId_ = other.ruleId_;
                    onChanged();
                }
                if (!other.getRuleStatus().isEmpty()) {
                    ruleStatus_ = other.ruleStatus_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private java.lang.Object ruleId_ = "";
            /**
             * <code>string ruleId = 1;</code>
             */
            public java.lang.String getRuleId() {
                java.lang.Object ref = ruleId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    ruleId_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string ruleId = 1;</code>
             */
            public com.google.protobuf.ByteString
            getRuleIdBytes() {
                java.lang.Object ref = ruleId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    ruleId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string ruleId = 1;</code>
             */
            public Builder setRuleId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                ruleId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string ruleId = 1;</code>
             */
            public Builder clearRuleId() {

                ruleId_ = getDefaultInstance().getRuleId();
                onChanged();
                return this;
            }
            /**
             * <code>string ruleId = 1;</code>
             */
            public Builder setRuleIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                ruleId_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object ruleStatus_ = "";
            /**
             * <code>string ruleStatus = 2;</code>
             */
            public java.lang.String getRuleStatus() {
                java.lang.Object ref = ruleStatus_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    ruleStatus_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string ruleStatus = 2;</code>
             */
            public com.google.protobuf.ByteString
            getRuleStatusBytes() {
                java.lang.Object ref = ruleStatus_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    ruleStatus_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string ruleStatus = 2;</code>
             */
            public Builder setRuleStatus(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                ruleStatus_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string ruleStatus = 2;</code>
             */
            public Builder clearRuleStatus() {

                ruleStatus_ = getDefaultInstance().getRuleStatus();
                onChanged();
                return this;
            }
            /**
             * <code>string ruleStatus = 2;</code>
             */
            public Builder setRuleStatusBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                ruleStatus_ = value;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:com.cruzeiro.repassedepolo.rulemanager.protobuf.ValidatedEvent)
        }

        // @@protoc_insertion_point(class_scope:com.cruzeiro.repassedepolo.rulemanager.protobuf.ValidatedEvent)
        private static final com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent();
        }

        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<ValidatedEvent>
                PARSER = new com.google.protobuf.AbstractParser<ValidatedEvent>() {
            public ValidatedEvent parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ValidatedEvent(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<ValidatedEvent> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ValidatedEvent> getParserForType() {
            return PARSER;
        }

        public com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.ValidatedEvent getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface RuleCmdOrBuilder extends
            // @@protoc_insertion_point(interface_extends:com.cruzeiro.repassedepolo.rulemanager.protobuf.RuleCmd)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string ruleId = 1;</code>
         */
        java.lang.String getRuleId();
        /**
         * <code>string ruleId = 1;</code>
         */
        com.google.protobuf.ByteString
        getRuleIdBytes();

        /**
         * <code>map&lt;string, string&gt; ruleDetails = 2;</code>
         */
        int getRuleDetailsCount();
        /**
         * <code>map&lt;string, string&gt; ruleDetails = 2;</code>
         */
        boolean containsRuleDetails(
                java.lang.String key);
        /**
         * Use {@link #getRuleDetailsMap()} instead.
         */
        @java.lang.Deprecated
        java.util.Map<java.lang.String, java.lang.String>
        getRuleDetails();
        /**
         * <code>map&lt;string, string&gt; ruleDetails = 2;</code>
         */
        java.util.Map<java.lang.String, java.lang.String>
        getRuleDetailsMap();
        /**
         * <code>map&lt;string, string&gt; ruleDetails = 2;</code>
         */

        java.lang.String getRuleDetailsOrDefault(
                java.lang.String key,
                java.lang.String defaultValue);
        /**
         * <code>map&lt;string, string&gt; ruleDetails = 2;</code>
         */

        java.lang.String getRuleDetailsOrThrow(
                java.lang.String key);
    }
    /**
     * Protobuf type {@code com.cruzeiro.repassedepolo.rulemanager.protobuf.RuleCmd}
     */
    public  static final class RuleCmd extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:com.cruzeiro.repassedepolo.rulemanager.protobuf.RuleCmd)
            RuleCmdOrBuilder {
        // Use RuleCmd.newBuilder() to construct.
        private RuleCmd(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private RuleCmd() {
            ruleId_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private RuleCmd(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            ruleId_ = s;
                            break;
                        }
                        case 18: {
                            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                                ruleDetails_ = com.google.protobuf.MapField.newMapField(
                                        RuleDetailsDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000002;
                            }
                            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                                    ruleDetails__ = input.readMessage(
                                    RuleDetailsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            ruleDetails_.getMutableMap().put(
                                    ruleDetails__.getKey(), ruleDetails__.getValue());
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 2:
                    return internalGetRuleDetails();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd.class, com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd.Builder.class);
        }

        private int bitField0_;
        public static final int RULEID_FIELD_NUMBER = 1;
        private volatile java.lang.Object ruleId_;
        /**
         * <code>string ruleId = 1;</code>
         */
        public java.lang.String getRuleId() {
            java.lang.Object ref = ruleId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                ruleId_ = s;
                return s;
            }
        }
        /**
         * <code>string ruleId = 1;</code>
         */
        public com.google.protobuf.ByteString
        getRuleIdBytes() {
            java.lang.Object ref = ruleId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                ruleId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int RULEDETAILS_FIELD_NUMBER = 2;
        private static final class RuleDetailsDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    java.lang.String, java.lang.String> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<java.lang.String, java.lang.String>newDefaultInstance(
                                    com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_RuleDetailsEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "");
        }
        private com.google.protobuf.MapField<
                java.lang.String, java.lang.String> ruleDetails_;
        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetRuleDetails() {
            if (ruleDetails_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        RuleDetailsDefaultEntryHolder.defaultEntry);
            }
            return ruleDetails_;
        }

        public int getRuleDetailsCount() {
            return internalGetRuleDetails().getMap().size();
        }
        /**
         * <code>map&lt;string, string&gt; ruleDetails = 2;</code>
         */

        public boolean containsRuleDetails(
                java.lang.String key) {
            if (key == null) { throw new java.lang.NullPointerException(); }
            return internalGetRuleDetails().getMap().containsKey(key);
        }
        /**
         * Use {@link #getRuleDetailsMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getRuleDetails() {
            return getRuleDetailsMap();
        }
        /**
         * <code>map&lt;string, string&gt; ruleDetails = 2;</code>
         */

        public java.util.Map<java.lang.String, java.lang.String> getRuleDetailsMap() {
            return internalGetRuleDetails().getMap();
        }
        /**
         * <code>map&lt;string, string&gt; ruleDetails = 2;</code>
         */

        public java.lang.String getRuleDetailsOrDefault(
                java.lang.String key,
                java.lang.String defaultValue) {
            if (key == null) { throw new java.lang.NullPointerException(); }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetRuleDetails().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;string, string&gt; ruleDetails = 2;</code>
         */

        public java.lang.String getRuleDetailsOrThrow(
                java.lang.String key) {
            if (key == null) { throw new java.lang.NullPointerException(); }
            java.util.Map<java.lang.String, java.lang.String> map =
                    internalGetRuleDetails().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getRuleIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ruleId_);
            }
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetRuleDetails(),
                            RuleDetailsDefaultEntryHolder.defaultEntry,
                            2);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getRuleIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ruleId_);
            }
            for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
                    : internalGetRuleDetails().getMap().entrySet()) {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                        ruleDetails__ = RuleDetailsDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, ruleDetails__);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd)) {
                return super.equals(obj);
            }
            com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd other = (com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd) obj;

            boolean result = true;
            result = result && getRuleId()
                    .equals(other.getRuleId());
            result = result && internalGetRuleDetails().equals(
                    other.internalGetRuleDetails());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + RULEID_FIELD_NUMBER;
            hash = (53 * hash) + getRuleId().hashCode();
            if (!internalGetRuleDetails().getMap().isEmpty()) {
                hash = (37 * hash) + RULEDETAILS_FIELD_NUMBER;
                hash = (53 * hash) + internalGetRuleDetails().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code com.cruzeiro.repassedepolo.rulemanager.protobuf.RuleCmd}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:com.cruzeiro.repassedepolo.rulemanager.protobuf.RuleCmd)
                com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmdOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 2:
                        return internalGetRuleDetails();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }
            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 2:
                        return internalGetMutableRuleDetails();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd.class, com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd.Builder.class);
            }

            // Construct using com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                ruleId_ = "";

                internalGetMutableRuleDetails().clear();
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_descriptor;
            }

            public com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd getDefaultInstanceForType() {
                return com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd.getDefaultInstance();
            }

            public com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd build() {
                com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd buildPartial() {
                com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd result = new com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.ruleId_ = ruleId_;
                result.ruleDetails_ = internalGetRuleDetails();
                result.ruleDetails_.makeImmutable();
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd) {
                    return mergeFrom((com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd other) {
                if (other == com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd.getDefaultInstance()) return this;
                if (!other.getRuleId().isEmpty()) {
                    ruleId_ = other.ruleId_;
                    onChanged();
                }
                internalGetMutableRuleDetails().mergeFrom(
                        other.internalGetRuleDetails());
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private java.lang.Object ruleId_ = "";
            /**
             * <code>string ruleId = 1;</code>
             */
            public java.lang.String getRuleId() {
                java.lang.Object ref = ruleId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    ruleId_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }
            /**
             * <code>string ruleId = 1;</code>
             */
            public com.google.protobuf.ByteString
            getRuleIdBytes() {
                java.lang.Object ref = ruleId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    ruleId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string ruleId = 1;</code>
             */
            public Builder setRuleId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                ruleId_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string ruleId = 1;</code>
             */
            public Builder clearRuleId() {

                ruleId_ = getDefaultInstance().getRuleId();
                onChanged();
                return this;
            }
            /**
             * <code>string ruleId = 1;</code>
             */
            public Builder setRuleIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                ruleId_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.MapField<
                    java.lang.String, java.lang.String> ruleDetails_;
            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetRuleDetails() {
                if (ruleDetails_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            RuleDetailsDefaultEntryHolder.defaultEntry);
                }
                return ruleDetails_;
            }
            private com.google.protobuf.MapField<java.lang.String, java.lang.String>
            internalGetMutableRuleDetails() {
                onChanged();;
                if (ruleDetails_ == null) {
                    ruleDetails_ = com.google.protobuf.MapField.newMapField(
                            RuleDetailsDefaultEntryHolder.defaultEntry);
                }
                if (!ruleDetails_.isMutable()) {
                    ruleDetails_ = ruleDetails_.copy();
                }
                return ruleDetails_;
            }

            public int getRuleDetailsCount() {
                return internalGetRuleDetails().getMap().size();
            }
            /**
             * <code>map&lt;string, string&gt; ruleDetails = 2;</code>
             */

            public boolean containsRuleDetails(
                    java.lang.String key) {
                if (key == null) { throw new java.lang.NullPointerException(); }
                return internalGetRuleDetails().getMap().containsKey(key);
            }
            /**
             * Use {@link #getRuleDetailsMap()} instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String> getRuleDetails() {
                return getRuleDetailsMap();
            }
            /**
             * <code>map&lt;string, string&gt; ruleDetails = 2;</code>
             */

            public java.util.Map<java.lang.String, java.lang.String> getRuleDetailsMap() {
                return internalGetRuleDetails().getMap();
            }
            /**
             * <code>map&lt;string, string&gt; ruleDetails = 2;</code>
             */

            public java.lang.String getRuleDetailsOrDefault(
                    java.lang.String key,
                    java.lang.String defaultValue) {
                if (key == null) { throw new java.lang.NullPointerException(); }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetRuleDetails().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }
            /**
             * <code>map&lt;string, string&gt; ruleDetails = 2;</code>
             */

            public java.lang.String getRuleDetailsOrThrow(
                    java.lang.String key) {
                if (key == null) { throw new java.lang.NullPointerException(); }
                java.util.Map<java.lang.String, java.lang.String> map =
                        internalGetRuleDetails().getMap();
                if (!map.containsKey(key)) {
                    throw new java.lang.IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearRuleDetails() {
                internalGetMutableRuleDetails().getMutableMap()
                        .clear();
                return this;
            }
            /**
             * <code>map&lt;string, string&gt; ruleDetails = 2;</code>
             */

            public Builder removeRuleDetails(
                    java.lang.String key) {
                if (key == null) { throw new java.lang.NullPointerException(); }
                internalGetMutableRuleDetails().getMutableMap()
                        .remove(key);
                return this;
            }
            /**
             * Use alternate mutation accessors instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, java.lang.String>
            getMutableRuleDetails() {
                return internalGetMutableRuleDetails().getMutableMap();
            }
            /**
             * <code>map&lt;string, string&gt; ruleDetails = 2;</code>
             */
            public Builder putRuleDetails(
                    java.lang.String key,
                    java.lang.String value) {
                if (key == null) { throw new java.lang.NullPointerException(); }
                if (value == null) { throw new java.lang.NullPointerException(); }
                internalGetMutableRuleDetails().getMutableMap()
                        .put(key, value);
                return this;
            }
            /**
             * <code>map&lt;string, string&gt; ruleDetails = 2;</code>
             */

            public Builder putAllRuleDetails(
                    java.util.Map<java.lang.String, java.lang.String> values) {
                internalGetMutableRuleDetails().getMutableMap()
                        .putAll(values);
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:com.cruzeiro.repassedepolo.rulemanager.protobuf.RuleCmd)
        }

        // @@protoc_insertion_point(class_scope:com.cruzeiro.repassedepolo.rulemanager.protobuf.RuleCmd)
        private static final com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd();
        }

        public static com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<RuleCmd>
                PARSER = new com.google.protobuf.AbstractParser<RuleCmd>() {
            public RuleCmd parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new RuleCmd(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<RuleCmd> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<RuleCmd> getParserForType() {
            return PARSER;
        }

        public com.cruzeiro.repassedepolo.rulemanager.protobuf.EventsAndCommands.RuleCmd getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleEvent_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleEvent_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_ValidatedEvent_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_ValidatedEvent_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_RuleDetailsEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_RuleDetailsEntry_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\027EventsAndCommands.proto\022/com.cruzeiro." +
                        "repassedepolo.rulemanager.protobuf\"/\n\tRu" +
                        "leEvent\022\016\n\006ruleId\030\001 \001(\t\022\022\n\nruleStatus\030\002 " +
                        "\001(\t\"4\n\016ValidatedEvent\022\016\n\006ruleId\030\001 \001(\t\022\022\n" +
                        "\nruleStatus\030\002 \001(\t\"\255\001\n\007RuleCmd\022\016\n\006ruleId\030" +
                        "\001 \001(\t\022^\n\013ruleDetails\030\002 \003(\0132I.com.cruzeir" +
                        "o.repassedepolo.rulemanager.protobuf.Rul" +
                        "eCmd.RuleDetailsEntry\0322\n\020RuleDetailsEntr" +
                        "y\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B3\n/com" +
                        ".cruzeiro.repassedepolo.rulemanager.prot",
                "obufH\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleEvent_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleEvent_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleEvent_descriptor,
                new java.lang.String[] { "RuleId", "RuleStatus", });
        internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_ValidatedEvent_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_ValidatedEvent_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_ValidatedEvent_descriptor,
                new java.lang.String[] { "RuleId", "RuleStatus", });
        internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_descriptor =
                getDescriptor().getMessageTypes().get(2);
        internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_descriptor,
                new java.lang.String[] { "RuleId", "RuleDetails", });
        internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_RuleDetailsEntry_descriptor =
                internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_descriptor.getNestedTypes().get(0);
        internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_RuleDetailsEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_com_cruzeiro_repassedepolo_rulemanager_protobuf_RuleCmd_RuleDetailsEntry_descriptor,
                new java.lang.String[] { "Key", "Value", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}